# Generated by Django 4.2.30 on 2026-05-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='included_amenities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='service',
            name='pricing_unit',
            field=models.CharField(choices=[('per_event', 'Per event'), ('per_guest', 'Per guest')], default='per_event', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='tier_prices',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
