# Generated by Django 4.2.30 on 2026-05-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_service_event_type_longer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='event_type',
            field=models.CharField(blank=True, default='', help_text='Comma-separated summary of event kinds; canonical list is event_types JSON.', max_length=500),
        ),
        migrations.AlterField(
            model_name='service',
            name='offering_label',
            field=models.CharField(blank=True, default='', help_text='Optional label when the same service type is listed more than once (e.g. Pakistani buffet vs continental).', max_length=120),
        ),
    ]
